AIM : To implement vanilla q learning algorithm

In [7]:
import numpy as np


In [8]:

# Define the environment
grid_size = 3
num_states = grid_size ** 2
num_actions = 4





Optimal Policy:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:

# Define the environment layout: S=start, G=goal, X=obstacle
env_layout = [
    ['S', ' ', 'X'],
    [' ', 'X', ' '],
    ['X', ' ', 'G']
]



In [11]:
# Define rewards: -1 for each step, 10 for reaching the goal, -10 for hitting an obstacle
rewards = {
    'S': -1,
    ' ': -1,
    'X': -10,
    'G': 10
}



In [12]:
# Define Q-table and initialize it with zeros
Q = np.zeros((num_states, num_actions))



In [13]:
# Hyperparameters
alpha = 0.1       # Learning rate
gamma = 0.9       # Discount factor
epsilon = 0.1     # Exploration rate
num_episodes = 1000



In [14]:
# Helper function to convert 2D coordinates to a 1D state index
def state_index(row, col):
    return row * grid_size + col



In [15]:
# Q-learning algorithm
for episode in range(num_episodes):
    state = state_index(0, 0)  # Start from the top-left corner
    done = False

    while not done:
        # Choose an action using epsilon-greedy policy
        if np.random.rand() < epsilon:
            action = np.random.randint(0, num_actions)  # Exploration: choose a random action
        else:
            action = np.argmax(Q[state, :])  # Exploitation: choose the action with the highest Q-value

        # Take the chosen action and observe the next state and reward
        row, col = divmod(state, grid_size)
        if action == 0:  # Up
            new_row = max(row - 1, 0)
            new_col = col
        elif action == 1:  # Down
            new_row = min(row + 1, grid_size - 1)
            new_col = col
        elif action == 2:  # Left
            new_row = row
            new_col = max(col - 1, 0)
        else:  # Right
            new_row = row
            new_col = min(col + 1, grid_size - 1)

        next_state = state_index(new_row, new_col)
        reward = rewards[env_layout[new_row][new_col]]

        # Q-value update using the Q-learning formula
        Q[state, action] += alpha * (reward + gamma * np.max(Q[next_state, :]) - Q[state, action])

        state = next_state

        if env_layout[new_row][new_col] in ('G', 'X'):
            done = True


In [16]:

print("Optimal Q-values:")


Optimal Q-values:


In [17]:
print(Q)# Extract the optimal policy (the action with the highest Q-value for each state)


[[-10. -10. -10. -10.]
 [-10. -10. -10. -10.]
 [  0.   0.   0.   0.]
 [-10. -10. -10. -10.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]


In [18]:
optimal_policy = np.argmax(Q, axis=1)
print("Optimal Policy:")


Optimal Policy:


In [19]:
print(optimal_policy.reshape(grid_size, grid_size))

[[2 0 0]
 [2 0 0]
 [0 0 0]]
